src/ZBlog/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZBlog.Models
{
    public class Post
    {
        public int Id { get; set; }

        [MaxLength(256)]
        public string Url { get; set; }

        public string Title { get; set; }

        public string Summary { get; set; }

        public string Content { get; set; }

        public DateTime CreateTime { get; set; }

        public DateTime LastEditTime { get; set; }

        public int Visits { get; set; }

        [ForeignKey("User")]
        public int? UserId { get; set; }

        public virtual User User { get; set; }

        [ForeignKey("Catalog")]
        [Display(Name = "Catalog")]
        public int? CatalogId { get; set; }

        public virtual Catalog Catalog { get; set; }

        public virtual ICollection<PostTag> PostTags { get; set; } = new List<PostTag>();
    }
}

src/ZBlog/Controllers/PostController.cs
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Microsoft.Extensions.Logging;
using ZBlog.Filters;
using ZBlog.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ZBlog.Controllers
{
    public class PostController : Controller
    {
        private readonly ZBlogDbContext _dbContext;
        private readonly ILogger _logger;

        public PostController(ZBlogDbContext dbContext, ILoggerFactory loggerFactory)
        {
            _dbContext = dbContext;
            _logger = loggerFactory.CreateLogger<PostController>();
        }

        // GET: /Post/Index
        [AdminRequired]
        public async Task<IActionResult> Index(ManageMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                message == ManageMessageId.PostNewSuccess ? "Your post has been posted."
                : message == ManageMessageId.PostEditSuccess ? "Your post has been updated."
                : message == ManageMessageId.PostDeleteSuccess ? "Your post has been deleted."
                : message == ManageMessageId.Error ? "An error has occurred."
                : "";

            var posts =
                await
                    _dbContext.Posts.Include(p => p.Catalog)
                        .Include(p => p.PostTags)
                        .ThenInclude(p => p.Tag)
                        .Include(p => p.User)
                        .OrderByDescending(p => p.CreateTime)
                        .ToListAsync();

            return View(posts);
        }

        // GET: /Post/{Url}
        [Route("Post/{Url}")]
        public async Task<IActionResult> Detail(string url)
        {
            if (string.IsNullOrWhiteSpace(url))
                return HttpNotFound();

            var post =
                await
                    _dbContext.Posts.Include(p => p.Catalog)
                        .Include(p => p.PostTags)
                        .ThenInclude(p => p.Tag)
                        .Include(p => p.User)
                        .OrderByDescending(p => p.CreateTime)
                        .SingleOrDefaultAsync(p => p.Url.Equals(url, StringComparison.OrdinalIgnoreCase));
            
            //todo add prev/next post

            return View(post);
        }

        // GET: /Post/New
        [AdminRequired]
        public async Task<IActionResult> New()
        {
            ViewBag.Catalogs = await _dbContext.Catalogs.OrderByDescending(c => c.PRI).ToListAsync();
            return View();
        }

        // POST: /Post/New
        [HttpPost]
        [AdminRequired]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> New(Post model, string tags, CancellationToken requestAborted)
        {
            if (ModelState.IsValid)
            {
                model.CreateTime = model.LastEditTime = DateTime.Now;
                model.Visits = 0;
                var length = model.Content.Length;
                model.Summary = model.Content.Substring(0, length >= 100 ? 100 : length);
                model.User = await GetCurrentUserAsync();
                _dbContext.Add(model);
                await _dbContext.SaveChangesAsync(requestAborted);
                if (!string.IsNullOrWhiteSpace(tags))
                {
                    await UpdatePostTags(model, tags, requestAborted);
                }
                _logger.LogDebug($"New post<{model.Title}>.");
                return RedirectToAction(nameof(Index), new { Message = ManageMessageId.PostNewSuccess });
            }
            var catalog = await _dbContext.Catalogs.OrderByDescending(c => c.PRI).ToListAsync(requestAborted);
            ViewBag.Catalogs = catalog;
            return View(model);
        }

        // GET: /Post/Edit/id
        [AdminRequired]
        public async Task<IActionResult> Edit(int? id)
        {
            _logger.LogDebug($"Edit post<{id}>");

            if (!id.HasValue)
            {
                return HttpNotFound();
            }

            var post = await _dbContext.Posts.Include(p => p.Catalog)
                .Include(p => p.PostTags)
                .ThenInclude(p => p.Tag)
                .Include(p => p.User).SingleOrDefaultAsync(p => p.Id == id);

            if (post == null)
            {
                return HttpNotFound();
            }

            ViewData["Title"] = $"Post Edit<{post.Title}>";
            
            ViewBag.Catalogs = await _dbContext.Catalogs.OrderByDescending(c => c.PRI).ToListAsync();

            return View(post);
        }

        // POST: /Post/Edit/id
        [HttpPost]
        [AdminRequired]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Post model, string tags, CancellationToken requestAborted)
        {
            if (ModelState.IsValid)
            {
                model.LastEditTime = DateTime.Now;
                var length = model.Content.Length;
                model.Summary = model.Content.Substring(0, length >= 100 ? 100 : length);
                model.User = await GetCurrentUserAsync();
                _dbContext.Update(model);
                await _dbContext.SaveChangesAsync(requestAborted);
                
                await UpdatePostTags(model, tags, requestAborted);
                
                _logger.LogDebug($"Updated post<{model.Title}>");

                return RedirectToAction(nameof(Index), new { Message = ManageMessageId.PostEditSuccess });
            }
            
            ViewBag.Catalogs = await _dbContext.Catalogs.OrderByDescending(c => c.PRI).ToListAsync(requestAborted);

            return View(model);
        }

        // GET: /Post/Delete/id
        [AdminRequired]
        public async Task<IActionResult> Delete(int? id)
        {
            _logger.LogDebug($"Delete post<{id}>");

            if (!id.HasValue)
            {
                return HttpNotFound();
            }

            var post = await _dbContext.Posts.SingleOrDefaultAsync(p => p.Id == id);

            if (post == null)
            {
                return HttpNotFound();
            }

            ViewData["Title"] = $"Post Delete<{post.Title}> Confirmation";
            
            return View(post);
        }

        // POST: /Post/Delete/id
        [HttpPost]
        [AdminRequired]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, CancellationToken requestAborted)
        {
            var post = await _dbContext.Posts.Include(p => p.PostTags)
                        .OrderByDescending(p => p.CreateTime)
                        .SingleOrDefaultAsync(p => p.Id == id, requestAborted);

            _dbContext.Remove(post);
            foreach (var postTag in post.PostTags)
            {
                //when count of the tag' posts less 1, then delete it.
                var tag = await _dbContext.Tags.Include(t => t.PostTags).SingleOrDefaultAsync(p => p.Id == postTag.TagId, requestAborted);
                if (tag.PostTags.Count <= 1)
                {
                    _dbContext.Remove(tag);
                }
                _dbContext.Remove(postTag);
            }
            
            await _dbContext.SaveChangesAsync(requestAborted);

            _logger.LogDebug($"Deleted post<{post.Title}>");

            return RedirectToAction(nameof(Index), new { Message = ManageMessageId.PostDeleteSuccess });
        }

        private async Task UpdatePostTags(Post model, string tags, CancellationToken requestAborted)
        {
            var postTags = _dbContext.PostTags.Where(p => p.PostId == model.Id);
            _logger.LogDebug($"Remove posttags count:{postTags.Count()}");
            _dbContext.PostTags.RemoveRange(postTags);
            await _dbContext.SaveChangesAsync(requestAborted);

            var tagArray = tags.Split(new[] {',', '，', ' '}, StringSplitOptions.RemoveEmptyEntries);
            foreach (var t in tagArray)
            {
                var postTag = new PostTag
                {
                    PostId = model.Id
                };
                var tag =
                    await _dbContext.Tags.FirstOrDefaultAsync(
                        x => x.Name.Equals(t, StringComparison.OrdinalIgnoreCase), requestAborted);
                if (tag == null)
                {
                    tag = new Tag
                    {
                        Name = t
                    };
                    _dbContext.Add(tag);
                    await _dbContext.SaveChangesAsync(requestAborted);
                }
                postTag.TagId = tag.Id;
                _dbContext.Add(postTag);
            }
            await _dbContext.SaveChangesAsync(requestAborted);
        }

        #region Helpers

        public enum ManageMessageId
        {
            PostNewSuccess,
            PostEditSuccess,
            PostDeleteSuccess,
            Error
        }

        private async Task<User> GetCurrentUserAsync()
        {
            return await _dbContext.Users.FirstOrDefaultAsync(u => u.Name.Equals(HttpContext.Session.GetString("AdminName")));
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }

        #endregion
    }
}

src/ZBlog/Views/Post/Delete.cshtml
@model Post

<h2>@ViewData["Title"]</h2>

<p>
    Are you sure you want to delete the post titled
    <strong>@Model.Title</strong>?
</p>

<form asp-controller="Post" asp-action="Delete" method="post" class="form-horizontal" role="form">
    <hr />
    <div class="am-form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="am-btn am-btn-primary">Delete</button>
            <button type="button" class="am-btn am-btn-secondary" onclick="window.history.go(-1);">Cancel</button>
        </div>
    </div>
</form>

src/ZBlog/Views/Post/Detail.cshtml
@model Post

@using CommonMark

@{
    ViewData["Title"] = Model.Title;
}

<article class="blog-main">
    <h3 class="am-article-title blog-title">
        <a asp-controller="Post" asp-action="Detail" asp-route-url="@Model.Url">@Model.Title</a>
        @if (Html.IsAdmin())
        {
            <a asp-controller="Post" asp-action="Edit" asp-route-id="@Model.Id" title="Edit"><i class="am-icon-btn am-success am-icon-edit"></i></a>
        }
    </h3>
    <h4 class="am-article-meta blog-meta">
        <span class="article-date"><i class="am-icon-calendar"></i> @Model.CreateTime.ToString("yyyy-MM-dd HH:mm")</span>
        <span class="article-user"><i class="am-icon-user"></i> <a asp-controller="Home" asp-action="Users" asp-route-name="@Model.User.NickName">@Model.User?.NickName</a></span>
        <span class="article-catalog"><i class="am-icon-folder-open-o"></i> <a asp-controller="Home" asp-action="Catalog" asp-route-title="@Model.Catalog?.Title">@Model.Catalog?.Title</a></span>
    </h4>

    <div class="am-g blog-content">
        <div class="am-u-sm-12">
            @Html.Raw(CommonMarkConverter.Convert(Model.Content))
        </div>
    </div>
    
    <h4 class="am-article-meta blog-meta">
        <span class="article-tag">
            <i class="am-icon-tags"></i>
            @foreach (var tag in Model.PostTags)
            {
                <span class="am-badge am-badge-success">
                    <a asp-controller="Home" asp-action="Tag" asp-route-name="@tag.Tag?.Name">@tag.Tag?.Name</a>
                </span>
            }
        </span>
    </h4>
</article>
<hr class="am-article-divider blog-hr">

<ul class="am-pagination blog-pagination">
    <li class="am-pagination-prev"><a id="page-prev" href="javascript:">&laquo; 上一页</a></li>
    <li class="am-pagination-next"><a id="page-next" href="javascript:">下一页 &raquo;</a></li>
</ul>

src/ZBlog/Views/Post/Edit.cshtml
@model Post

<h2>@ViewData["Title"]</h2>

<form asp-controller="Post" asp-action="Edit" method="post" class="form-horizontal" role="form">
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <input asp-for="Id" class="am-form-field" type="hidden"/>
    <input asp-for="CreateTime" class="am-form-field" type="hidden"/>
    <input asp-for="LastEditTime" class="am-form-field" type="hidden"/>
    <input asp-for="Visits" class="am-form-field" type="hidden" />
    <div class="am-form-group">
        <label asp-for="Title" class="col-md-2 am-form-label"></label>
        <div class="col-md-10">
            <input asp-for="Title" class="am-form-field" placeholder="Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label asp-for="Url" class="col-md-2 am-form-label"></label>
        <div class="col-md-10">
            <input asp-for="Url" class="am-form-field" placeholder="Post url" />
            <span asp-validation-for="Url" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label asp-for="Content" class="col-md-2 am-form-label"></label>
        <div class="col-md-10">
            <textarea asp-for="Content" class="am-form-field" placeholder="Write something here"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label asp-for="CatalogId" class="col-md-2 am-form-label"></label>
        <div class="col-md-10">
            <select asp-for="CatalogId" class="am-form-field">
                @foreach (Catalog c in ViewBag.Catalogs)
                {
                    <!option value="@c.Id" @(Model?.CatalogId == c.Id ? "selected" : "")>@c.Title</!option>
                }
            </select>
            <span asp-validation-for="CatalogId" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label for="Tags" class="col-md-2 am-form-label">Tag</label>
        <div class="col-md-10">
            <input id="Tags" name="Tags" class="am-form-field" placeholder="Use a ',' to split tags" value="@string.Join(",", Model.PostTags.Select(t => t.Tag.Name))" />
        </div>
    </div>
    <div class="am-form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="am-btn am-btn-primary">Update</button>
            <button type="button" class="am-btn am-btn-secondary" onclick="window.history.go(-1);">Cancel</button>
        </div>
    </div>
</form>

@section Scripts {
    <script type="text/javascript">
        var simplemde = new SimpleMDE({ element: $("#Content")[0] });
    </script>
}

src/ZBlog/Views/Post/Index.cshtml
@model List<Post>
@{
    ViewData["Title"] = "Post List";
}

<h2>@ViewData["Title"]</h2>
<p class="text-success">@ViewData["StatusMessage"]</p>
<div>
    <table class="am-table am-table-bordered am-table-striped am-table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Url</th>
                <th>Catalog</th>
                <th>Tag</th>
                <th>CreateTime</th>
                <th>LastEditTime</th>
                <th>User</th>
                <th>Manage</th>
            </tr>
        </thead>
        <tbody>
         @foreach (Post post in Model)
         {
             <tr>
                 <td>@post.Title</td>
                 <td>@post.Url</td>
                 <td>@post.Catalog.Title</td>
                 <td>@string.Join(",", post.PostTags.Select(t => t.Tag.Name))</td>
                 <td>@post.CreateTime.ToString("yyyy-MM-dd HH:mm")</td>
                 <td>@post.LastEditTime.ToString("yyyy-MM-dd HH:mm")</td>
                 <td>@post.User.Name</td>
                 <td>
                     <a asp-controller="Post" asp-action="Edit" asp-route-id="@post.Id">Edit</a>
                     <a asp-controller="Post" asp-action="Delete" asp-route-id="@post.Id">Delete</a>
                 </td>
             </tr>
         }
        </tbody>
    </table>
</div>

src/ZBlog/Views/Post/New.cshtml
@model Post

@{
    ViewData["Title"] = "New Post";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Post" asp-action="New" method="post" class="form-horizontal" role="form">
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="am-form-group">
        <label asp-for="Title" class="col-md-2 am-form-label"></label>
        <div class="col-md-10">
            <input asp-for="Title" class="am-form-field" placeholder="Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label asp-for="Url" class="col-md-2 am-form-label"></label>
        <div class="col-md-10">
            <input asp-for="Url" class="am-form-field" placeholder="Post url" />
            <span asp-validation-for="Url" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label asp-for="Content" class="col-md-2 am-form-label"></label>
        <div class="col-md-10">
            <textarea asp-for="Content" class="am-form-field" placeholder="Write something here"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label asp-for="CatalogId" class="col-md-2 am-form-label"></label>
        <div class="col-md-10">
            <select asp-for="CatalogId" class="am-form-field">
                <option value="0">None</option>
                @foreach (Catalog c in ViewBag.Catalogs)
                {
                    <!option value="@c.Id" @(Model?.CatalogId == c.Id ? "selected" : "")>@c.Title</!option>
                }
            </select>
            <span asp-validation-for="CatalogId" class="text-danger"></span>
        </div>
    </div>
    <div class="am-form-group">
        <label for="Tags" class="col-md-2 am-form-label">Tag</label>
        <div class="col-md-10">
            <input id="Tags" name="Tags" class="am-form-field" placeholder="Use a ',' to split tags" />
        </div>
    </div>
    <div class="am-form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="am-btn am-btn-primary">Submit</button>
            <button type="button" class="am-btn am-btn-secondary" onclick="window.history.go(-1);">Cancel</button>
        </div>
    </div>
</form>

@section Scripts {
    <script type="text/javascript">
        var simplemde = new SimpleMDE({ element: $("#Content")[0] });
    </script>
}